upload:
	scp * neoneye@rubyforge.org:/var/www/gforge-projects/aeditor/

upload_shots:
	scp -r aeditor_shots neoneye@rubyforge.org:/var/www/gforge-projects/aeditor/

upload_graphics:
	scp -r graphics neoneye@rubyforge.org:/var/www/gforge-projects/aeditor/
