#g++ main.cpp -I/home/neoneye/include/fox /home/neoneye/lib/libFOX.so

#FLAGS = -I/home/neoneye/include/fox /home/neoneye/lib/libFOX.so
FLAGS = -I/usr/local/include/fox /usr/local/lib/libFOX.so

all:
	g++ -Wall main.cpp ${FLAGS}
