upload:
	scp *.html neoneye@rubyforge.org:/var/www/gforge-projects/aeditor/

upload_all:
	scp *.html *.png neoneye@rubyforge.org:/var/www/gforge-projects/aeditor/

test:
	cp *.html *.png ~/web/test/.

